### ISSUE TITLE
Fix Link Component

### ISSUE THREAD

**Issue by ScriptedAlchemy** [zackljackson/redux-first-router#16]
NavLink seems to work, but Link is not working anymore with `rudy-respond` Some crucial elements to consider in Link are preloading, prefetching, and preloading without rendering the <Link on the page. 

I was thinking about webpack preload magic comments, which will require some updates to universal

**Comment by hedgepigdaniel** [comment]
Fixed by https://github.com/ScriptedAlchemy/redux-first-router/pull/19, although its still in the `lerna` branch and not `rudy-respond` (cherry-picking would be fairly easy though)
